In [42]:
import pandas as pd
import numpy as np

<h2>DATA PREPROCESSING<H2>

In [43]:
liked_posts = pd.read_csv("C:\\Users\\kirut\\PycharmProjects\\codebasics\\VideoRecommendationSystem\\data\\cleaned_liked_post.csv")
rated_posts = pd.read_csv("C:\\Users\\kirut\\PycharmProjects\\codebasics\\VideoRecommendationSystem\\data\\cleaned_rated_post.csv")
view_posts = pd.read_csv("C:\\Users\\kirut\\PycharmProjects\\codebasics\\VideoRecommendationSystem\\data\\cleaned_viewed_post.csv")
inspired_posts=pd.read_csv("C:\\Users\\kirut\\PycharmProjects\\codebasics\\VideoRecommendationSystem\\data\\cleaned_inspired_post.csv")
all_posts=pd.read_csv("C:\\Users\\kirut\\PycharmProjects\\codebasics\\VideoRecommendationSystem\\data\\cleaned_all_post.csv")
all_users=pd.read_csv("C:\\Users\\kirut\\PycharmProjects\\codebasics\\VideoRecommendationSystem\\data\\cleaned_all_users.csv")


In [44]:
#Cleaning each dataset  before concat
for df in [liked_posts, rated_posts, view_posts, inspired_posts, all_posts, all_users]:
    df.drop_duplicates(inplace=True)


In [45]:
# Standardize key columns
for df in [liked_posts, rated_posts, view_posts, inspired_posts, all_posts, all_users]:
    df['id'] = df['id'].astype(int)

In [46]:
all_users['username'] = all_users['username'].str.lower().str.strip()

In [47]:
# Check for missing values in each dataset
print("Missing values in liked_posts:")
print(liked_posts.isnull().sum())

print("Missing values in rated_posts:")
print(rated_posts.isnull().sum())

print("Missing values in view_posts:")
print(view_posts.isnull().sum())

print("Missing values in inspired_posts:")
print(inspired_posts.isnull().sum())

print("Missing values in all_posts:")
print(all_posts.isnull().sum())

print("Missing values in all_users:")
print(all_users.isnull().sum())

Missing values in liked_posts:
id                       0
slug                     0
title                   15
identifier               0
comment_count            0
upvote_count             0
view_count               0
exit_count               0
rating_count             0
average_rating           0
share_count              0
video_link               0
contract_address        59
chain_id                59
chart_url               59
is_locked                0
created_at               0
first_name               0
last_name                0
username                 0
upvoted                  0
bookmarked               0
gif_thumbnail_url       51
following                0
baseToken_address       59
baseToken_name          59
baseToken_symbol        59
baseToken_image_url     59
category_id              0
category_name            0
category_count           0
category_description     0
category_image_url       0
total_interactions       0
dtype: int64
Missing values in rated_posts:
id     

In [48]:
#HAndling missimng values in Interaction Datasets Liked_post,Inspired_post,Rated_post,Viewed_post
# Columns to drop
drop_columns_posts = ['contract_address', 'chain_id', 'chart_url', 'gif_thumbnail_url',
                      'baseToken_address', 'baseToken_name', 'baseToken_symbol', 'baseToken_image_url']

# Apply transformations to all datasets
for df in [liked_posts, rated_posts, view_posts, inspired_posts]:
    df.drop(columns=drop_columns_posts, inplace=True)
    df.fillna({
        'title': 'Unknown Title',
        'category_name': 'general',
        'view_count': 0,
        'comment_count': 0,
        'upvote_count': 0,
        'share_count': 0,
    }, inplace=True)
    # Drop rows with missing IDs or usernames
    df.dropna(subset=['id', 'username'], inplace=True)

In [11]:
print("Missing values in liked_posts:")
print(liked_posts.isnull().sum())

print("Missing values in rated_posts:")
print(rated_posts.isnull().sum())

print("Missing values in view_posts:")
print(view_posts.isnull().sum())

print("Missing values in inspired_posts:")
print(inspired_posts.isnull().sum())

Missing values in liked_posts:
id                      0
slug                    0
title                   0
identifier              0
comment_count           0
upvote_count            0
view_count              0
exit_count              0
rating_count            0
average_rating          0
share_count             0
video_link              0
is_locked               0
created_at              0
first_name              0
last_name               0
username                0
upvoted                 0
bookmarked              0
following               0
category_id             0
category_name           0
category_count          0
category_description    0
category_image_url      0
total_interactions      0
dtype: int64
Missing values in rated_posts:
id                      0
slug                    0
title                   0
identifier              0
comment_count           0
upvote_count            0
view_count              0
exit_count              0
rating_count            0
average_rating 

In [49]:
#Handling Missing values in All_post dataset
# Columns to drop
drop_columns_all_posts = ['contract_address', 'chain_id', 'chart_url', 'gif_thumbnail_url',
                          'baseToken_address', 'baseToken_name', 'baseToken_symbol', 'baseToken_image_url']

# Transformations for all_posts
all_posts.drop(columns=drop_columns_all_posts, inplace=True)
all_posts.fillna({
    'title': 'Unknown Title',
    'category_name': 'general',
    'view_count': 0,
    'comment_count': 0,
    'upvote_count': 0,
    'share_count': 0,
}, inplace=True)
all_posts.dropna(subset=['id'], inplace=True)


In [50]:
print("Missing values in all_posts:")
print(all_posts.isnull().sum())

Missing values in all_posts:
id                      0
slug                    0
title                   0
identifier              0
comment_count           0
upvote_count            0
view_count              0
exit_count              0
rating_count            0
average_rating          0
share_count             0
video_link              0
is_locked               0
created_at              0
first_name              0
last_name               0
username                0
upvoted                 0
bookmarked              0
following               0
category_id             0
category_name           0
category_count          0
category_description    0
category_image_url      0
dtype: int64


In [51]:
#Handling missing values in All_Users
# Columns to drop
drop_columns_users = ['bio', 'website_url', 'instagram-url', 'youtube_url', 'tictok_url', 
                      'referral_code', 'latitude', 'longitude', 'has_wallet']

# Transformations for all_users
all_users.drop(columns=drop_columns_users, inplace=True)
all_users.fillna({
    'username': 'unknown_user',
    'email': 'unknown@example.com',
    'last_login': '2024-01-01',
    'follower_count': 0,
    'following_count': 0,
    'post_count': 0,
    'share_count': 0,
}, inplace=True)

In [52]:
print("Missing values in all_users:")
print(all_users.isnull().sum())

Missing values in all_users:
id                 0
first_name         0
last_name          0
username           0
email              0
role               0
profile_url        0
isVerified         0
last_login         0
share_count        0
post_count         0
following_count    0
follower_count     0
is_verified        0
is_online          0
dtype: int64


In [53]:
all_users['last_login']

0       2024-12-05 15:21:15
1                2024-01-01
2                2024-01-01
3                2024-01-01
4       2024-12-06 02:20:32
               ...         
1125    2024-12-05 18:14:28
1126    2024-12-05 16:18:37
1127    2024-12-05 16:21:45
1128             2024-01-01
1129             2024-01-01
Name: last_login, Length: 1130, dtype: object

In [54]:
# Add interaction type column
liked_posts['interaction_type'] = 'like'
rated_posts['interaction_type'] = 'rate'
view_posts['interaction_type'] = 'view'
inspired_posts['interaction_type'] = 'inspire'


In [55]:
# Concatenate all interaction datasets
interactions = pd.concat([liked_posts, rated_posts, view_posts, inspired_posts], ignore_index=True)


In [56]:
interactions.columns

Index(['id', 'slug', 'title', 'identifier', 'comment_count', 'upvote_count',
       'view_count', 'exit_count', 'rating_count', 'average_rating',
       'share_count', 'video_link', 'is_locked', 'created_at', 'first_name',
       'last_name', 'username', 'upvoted', 'bookmarked', 'following',
       'category_id', 'category_name', 'category_count',
       'category_description', 'category_image_url', 'total_interactions',
       'interaction_type', 'engagement_score', 'interaction_rate'],
      dtype='object')

In [57]:
columns_to_retain = [
    'id', 'title', 'comment_count', 'upvote_count', 'view_count', 'rating_count',
    'average_rating', 'share_count','exit_count', 'created_at', 'username', 'interaction_type',
    'engagement_score', 'interaction_rate','category_id','video_link'
]
interactions = interactions[columns_to_retain]

In [58]:
interactions.isnull().sum()

id                    0
title                 0
comment_count         0
upvote_count          0
view_count            0
rating_count          0
average_rating        0
share_count           0
exit_count            0
created_at            0
username              0
interaction_type      0
engagement_score    267
interaction_rate    267
category_id           0
video_link            0
dtype: int64

In [59]:
interactions['engagement_score'] = (interactions['view_count'] + interactions['upvote_count'] - interactions['exit_count']) / (interactions['view_count'] + 1)
interactions['interaction_rate'] = interactions['upvote_count'] / (interactions['view_count'] + 1)

In [60]:
interactions.isnull().sum()

id                  0
title               0
comment_count       0
upvote_count        0
view_count          0
rating_count        0
average_rating      0
share_count         0
exit_count          0
created_at          0
username            0
interaction_type    0
engagement_score    0
interaction_rate    0
category_id         0
video_link          0
dtype: int64

In [61]:
interactions.to_csv("data/cleaned_interactions2.csv", index=False)

In [62]:
all_posts.columns

Index(['id', 'slug', 'title', 'identifier', 'comment_count', 'upvote_count',
       'view_count', 'exit_count', 'rating_count', 'average_rating',
       'share_count', 'video_link', 'is_locked', 'created_at', 'first_name',
       'last_name', 'username', 'upvoted', 'bookmarked', 'following',
       'category_id', 'category_name', 'category_count',
       'category_description', 'category_image_url'],
      dtype='object')

In [63]:
columns_to_retain = [
    'id', 'title', 'comment_count', 'upvote_count', 'view_count', 'rating_count',
    'average_rating', 'share_count','exit_count', 'created_at', 'username','category_name','category_count','category_description'
]
all_posts=all_posts[columns_to_retain]

In [64]:
#Merge Interaction Data with Posts
merged_data = pd.merge(interactions, all_posts, on='id', how='inner')

In [65]:
merged_data.columns

Index(['id', 'title_x', 'comment_count_x', 'upvote_count_x', 'view_count_x',
       'rating_count_x', 'average_rating_x', 'share_count_x', 'exit_count_x',
       'created_at_x', 'username_x', 'interaction_type', 'engagement_score',
       'interaction_rate', 'category_id', 'video_link', 'title_y',
       'comment_count_y', 'upvote_count_y', 'view_count_y', 'rating_count_y',
       'average_rating_y', 'share_count_y', 'exit_count_y', 'created_at_y',
       'username_y', 'category_name', 'category_count',
       'category_description'],
      dtype='object')

In [66]:
merged_data = merged_data.drop(columns=['title_y', 'comment_count_y', 'upvote_count_y', 
                                       'view_count_y', 'rating_count_y', 'average_rating_y', 
                                       'share_count_y', 'created_at_y', 'username_y', 
                                       'exit_count_y'])

In [67]:
merged_data.rename(columns={
    'username_x': 'username',
    'title_x': 'title',
    'comment_count_x':'comment_count',
    'upvote_count_x':'upvote_count',
    'view_count_x':'view_count',
 'rating_count_x': 'rating_count',
     'average_rating_x': 'average_rating',
    'share_count_x':'share_count',
    'exit_count_x':'exit_count',
    'created_at_x': 'created_at'
}, inplace=True)

In [68]:
merged_data.columns

Index(['id', 'title', 'comment_count', 'upvote_count', 'view_count',
       'rating_count', 'average_rating', 'share_count', 'exit_count',
       'created_at', 'username', 'interaction_type', 'engagement_score',
       'interaction_rate', 'category_id', 'video_link', 'category_name',
       'category_count', 'category_description'],
      dtype='object')

In [69]:
all_users.columns

Index(['id', 'first_name', 'last_name', 'username', 'email', 'role',
       'profile_url', 'isVerified', 'last_login', 'share_count', 'post_count',
       'following_count', 'follower_count', 'is_verified', 'is_online'],
      dtype='object')

In [70]:
columns_to_retain = [
    'id', 'username', 'email', 'first_name', 'last_name', 'role', 'profile_url',
    'isVerified', 'last_login', 'share_count', 'post_count',
    'following_count', 'follower_count'
]
all_users=all_users[columns_to_retain]

In [71]:
all_users.columns

Index(['id', 'username', 'email', 'first_name', 'last_name', 'role',
       'profile_url', 'isVerified', 'last_login', 'share_count', 'post_count',
       'following_count', 'follower_count'],
      dtype='object')

In [72]:
#Merge User Data
final_data = pd.merge(merged_data, all_users, on='username', how='inner')

In [73]:
final_data.columns

Index(['id_x', 'title', 'comment_count', 'upvote_count', 'view_count',
       'rating_count', 'average_rating', 'share_count_x', 'exit_count',
       'created_at', 'username', 'interaction_type', 'engagement_score',
       'interaction_rate', 'category_id', 'video_link', 'category_name',
       'category_count', 'category_description', 'id_y', 'email', 'first_name',
       'last_name', 'role', 'profile_url', 'isVerified', 'last_login',
       'share_count_y', 'post_count', 'following_count', 'follower_count'],
      dtype='object')

In [74]:
final_data=final_data.drop(columns=['id_y','share_count_y'])
final_data.columns


Index(['id_x', 'title', 'comment_count', 'upvote_count', 'view_count',
       'rating_count', 'average_rating', 'share_count_x', 'exit_count',
       'created_at', 'username', 'interaction_type', 'engagement_score',
       'interaction_rate', 'category_id', 'video_link', 'category_name',
       'category_count', 'category_description', 'email', 'first_name',
       'last_name', 'role', 'profile_url', 'isVerified', 'last_login',
       'post_count', 'following_count', 'follower_count'],
      dtype='object')

In [75]:
final_data.rename(columns={'id_x':'id','share_count_x':'share_count'},inplace=True)

In [76]:
final_data.columns

Index(['id', 'title', 'comment_count', 'upvote_count', 'view_count',
       'rating_count', 'average_rating', 'share_count', 'exit_count',
       'created_at', 'username', 'interaction_type', 'engagement_score',
       'interaction_rate', 'category_id', 'video_link', 'category_name',
       'category_count', 'category_description', 'email', 'first_name',
       'last_name', 'role', 'profile_url', 'isVerified', 'last_login',
       'post_count', 'following_count', 'follower_count'],
      dtype='object')

In [35]:
final_data.to_csv("data/finaldata.csv",index=False)

In [36]:
final_data['average_rating'].max()

83

<h2>FEATURE ENGINEERING<h2>

In [77]:
final_data['category_name'].unique()


array(['Bloom Scroll', 'Pumptok', 'Vible', 'SolTok', 'InstaRama', 'E/ACC',
       'Flic', 'Gratitube'], dtype=object)

In [78]:
#Creating mood column based on Category_name
# Mood mapping based on category name
category_mood_map = {
    'Bloom Scroll': 'Happy',
    'Pumptok': 'Excited',
    'Vible': 'Happy',
    'SolTok': 'Neutral',
    'InstaRama': 'Happy',
    'E/ACC': 'Neutral',
    'Flic': 'Excited',
    'Gratitube': 'Happy'
}

# Function to map category_name to mood
def get_mood_from_category(category_name):
    return category_mood_map.get(category_name, 'Neutral')  # Default to Neutral if not in map

# Apply the function to create a new 'mood' column
final_data['mood'] = final_data['category_name'].apply(get_mood_from_category)

# View the result
print(final_data[['id', 'category_name', 'mood']])

       id category_name     mood
0    1379  Bloom Scroll    Happy
1    1379  Bloom Scroll    Happy
2    1379  Bloom Scroll    Happy
3    1380  Bloom Scroll    Happy
4    1380  Bloom Scroll    Happy
..    ...           ...      ...
407    56         Vible    Happy
408    40         Vible    Happy
409    40         Vible    Happy
410   633         Vible    Happy
411  1340        SolTok  Neutral

[412 rows x 3 columns]


In [103]:
final_data.columns

Index(['id', 'title', 'comment_count', 'upvote_count', 'view_count',
       'rating_count', 'average_rating', 'share_count', 'exit_count',
       'created_at', 'username', 'interaction_type', 'engagement_score',
       'interaction_rate', 'category_id', 'video_link', 'category_name',
       'category_count', 'category_description', 'email', 'first_name',
       'last_name', 'role', 'profile_url', 'isVerified', 'last_login',
       'post_count', 'following_count', 'follower_count', 'mood', 'content'],
      dtype='object')

In [80]:
final_data.to_csv("data/featureengineering.csv",index=False)

<h2>ALGORITHM DEVELOPMENT</h2>

**1.CONTENT-BASED FILTERING**

In [156]:
df=final_data
# Combine category_name and category_description into a single column
df['content'] = df['category_name'] + " " + df['category_description']
print(df['content'].head(2))

0    Bloom Scroll Scroll until you bloom
1    Bloom Scroll Scroll until you bloom
Name: content, dtype: object


In [157]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the TF-IDF Vectorizer
vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2), max_features=5000)

# Fit and transform the content column
tfidf_matrix = vectorizer.fit_transform(df['content'])

# Check the shape of the resulting TF-IDF matrix
print(tfidf_matrix.shape)

(412, 57)


In [158]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['normalized_engagement'] = scaler.fit_transform(df[['engagement_score']])

In [147]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute the cosine similarity matrix
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Check the shape of the similarity matrix
print(cosine_sim.shape)

(412, 412)


In [159]:
def get_recommendations(post_id, cosine_sim, df, top_n=5):
     # Get the pairwise similarity scores for the given post
    sim_scores = list(enumerate(cosine_sim[post_id]))
    
    # Sort by similarity score in descending order
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the top_n similar posts (excluding the post itself)
    sim_scores = sim_scores[1:top_n+1]
    
    # Get the post indices
    post_indices = [i[0] for i in sim_scores]
    predicted_scores = [i[1] for i in sim_scores]
    recommendations = df.iloc[post_indices].copy()
    recommendations['predicted_score'] = predicted_scores
    
    return recommendations

In [161]:
# Example: Get recommendations for the video at index 10
recommended_posts = get_recommendations(10, cosine_sim, df, top_n=5)

# Display the recommended posts with relevant details
print(recommended_posts[['id', 'title', 'category_name', 'normalized_engagement','video_link','predicted_score']])

     id                                              title category_name  \
1  1379  When the heart and the mind work together.. ❤️...  Bloom Scroll   
2  1379  When the heart and the mind work together.. ❤️...  Bloom Scroll   
3  1380  This reminder is so important 🌻↓\n\nHave you p...  Bloom Scroll   
4  1380  This reminder is so important 🌻↓\n\nHave you p...  Bloom Scroll   
5  1380  This reminder is so important 🌻↓\n\nHave you p...  Bloom Scroll   

   normalized_engagement                                         video_link  \
1               0.467583  https://video-cdn.socialverseapp.com/bloomscro...   
2               0.467583  https://video-cdn.socialverseapp.com/bloomscro...   
3               0.559136  https://video-cdn.socialverseapp.com/bloomscro...   
4               0.559136  https://video-cdn.socialverseapp.com/bloomscro...   
5               0.559136  https://video-cdn.socialverseapp.com/bloomscro...   

   predicted_score  
1              1.0  
2              1.0  
3    

**2.COLLABORATIVE FILTERING USER-BASED**

In [95]:
# Create the user-item interaction matrix
interaction_matrix = df.pivot_table(index='username', columns='id', values='engagement_score', fill_value=0)

# Display the interaction matrix
print(interaction_matrix.head())

id                  11        14        15        16       19        23    \
username                                                                    
afrobeezy       1.709677  1.666667  1.887324  1.617647  1.34058  1.520548   
bloomscroller   0.000000  0.000000  0.000000  0.000000  0.00000  0.000000   
kinha           0.000000  0.000000  0.000000  0.000000  0.00000  0.000000   
michaeldadziie  0.000000  0.000000  0.000000  0.000000  0.00000  0.000000   
mike            0.000000  0.000000  0.000000  0.000000  0.00000  0.000000   

id                  29        30        31       32    ...       1375    1376  \
username                                               ...                      
afrobeezy       1.546667  1.846154  1.331034  1.74026  ...   0.000000   0.000   
bloomscroller   0.000000  0.000000  0.000000  0.00000  ...   0.000000   0.000   
kinha           0.000000  0.000000  0.000000  0.00000  ... -26.071429 -21.625   
michaeldadziie  0.000000  0.000000  0.000000  0.00000  

In [100]:
from sklearn.preprocessing import StandardScaler

# Normalize the engagement score to handle varying scales
scaler = StandardScaler()
interaction_matrix_scaled = scaler.fit_transform(interaction_matrix)

print(interaction_matrix_scaled[:5, :5])

[[ 3.          3.          3.          3.          3.        ]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333]]


In [104]:
# Create a unique user identifier (using 'username' for simplicity)
df['user_id'] = df['username'] 

In [105]:
# Use KNN for User-Based Collaborative Filtering
model = NearestNeighbors(n_neighbors=5, metric='cosine', algorithm='auto')
model.fit(interaction_matrix.values)  # Fit the model on the interaction matrix


NearestNeighbors(metric='cosine')

In [109]:
# Recommend Posts for a Specific User
def recommend_for_user(user_id, interaction_matrix, model, top_n=5):
    # Check if user_id is in the interaction matrix
    if user_id not in interaction_matrix.index:
        return f"User {user_id} not found in the dataset."
    
    # Get the index of the user in the interaction matrix
    user_index = interaction_matrix.index.get_loc(user_id)

    # Find the nearest neighbors (similar users) for the given user
    distances, indices = model.kneighbors(interaction_matrix.iloc[user_index].values.reshape(1, -1))

    # Get the list of similar users
    similar_users = interaction_matrix.index[indices[0]]

    # Get the list of posts the user has already interacted with
    interacted_items = interaction_matrix.iloc[user_index][interaction_matrix.iloc[user_index] > 0].index
    all_items = interaction_matrix.columns

    # Filter out the posts the user has already interacted with
    items_to_predict = [item for item in all_items if item not in interacted_items]

    # Predict the scores for non-interacted posts based on similar users' engagement
    predictions = []
    for item in items_to_predict:
        weighted_ratings = 0
        total_similarity = 0
        for similar_user in similar_users:
            if interaction_matrix.loc[similar_user, item] > 0:  # Check if similar user interacted with the item
                # Add the weighted engagement score from similar user
                weighted_ratings += interaction_matrix.loc[similar_user, item] * (1 / (1 + distances[0][similar_users.get_loc(similar_user)]))
                total_similarity += 1

        if total_similarity > 0:
            predictions.append((item, weighted_ratings / total_similarity))

    # Sort predictions by predicted engagement score in descending order
    top_predictions = sorted(predictions, key=lambda x: x[1], reverse=True)[:top_n]

     # Create a DataFrame with additional information for the recommended items
    recommended_items = []
    for item, score in top_predictions:
        item_info = df[df['id'] == item][['id', 'category_name', 'video_link']].iloc[0]
        recommended_items.append({
            'id': item_info['id'],
            'category_name': item_info['category_name'],
            'video_link': item_info['video_link'],
            'predicted_score': score
        })

    return pd.DataFrame(recommended_items)


In [113]:
user_id = 'mike'
recommendations = recommend_for_user(user_id, interaction_matrix, model)
print("Recommended Posts for User:")
print(recommendations)

Recommended Posts for User:
    id category_name                                         video_link  \
0   34         Vible  https://video-cdn.socialverseapp.com/afrobeezy...   
1  459     Gratitube  https://video-cdn.socialverseapp.com/swapnil_a...   
2   35         Vible  https://video-cdn.socialverseapp.com/afrobeezy...   
3   61         E/ACC  https://video-cdn.socialverseapp.com/afrobeezy...   
4   15         Vible  https://video-cdn.socialverseapp.com/michael_b...   

   predicted_score  
0         1.391892  
1         1.229508  
2         1.192308  
3         1.116279  
4         0.943662  


**3.Hybrid Model**

In [188]:
# Create a TF-IDF matrix for the content (title + category_name)
vectorizer = TfidfVectorizer(stop_words='english')
content_matrix = vectorizer.fit_transform(df['content'])


In [189]:
# Calculate cosine similarity between items based on content features
content_similarities = cosine_similarity(content_matrix)


In [190]:
interaction_matrix = df.pivot_table(index='username', columns='id', values='normalized_engagement', fill_value=0)
from sklearn.preprocessing import StandardScaler

# Normalize the engagement score to handle varying scales
scaler = StandardScaler()
interaction_matrix_scaled = scaler.fit_transform(interaction_matrix)

print(interaction_matrix_scaled[:5, :5])

[[ 3.          3.          3.          3.          3.        ]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333]]


In [191]:
df['user_id'] = df['username'] 

In [192]:
# Create an item-item similarity matrix using the engagement score
item_model = NearestNeighbors(n_neighbors=5, metric='cosine', algorithm='auto')
item_model.fit(interaction_matrix.T.values)  # Fit on transposed interaction matrix (item-based)

NearestNeighbors(metric='cosine')

In [195]:
#Hybrid Model - Combine content-based and item-based recommendations
#  alpha is the weight given to content-based filtering (0 to 1).
def hybrid_recommendation(user_id, interaction_matrix, item_model, content_similarities, df, top_n=5, alpha=0.5):
     if user_id not in interaction_matrix.index:
        return f"User {user_id} not found in the dataset."
     user_index = interaction_matrix.index.get_loc(user_id)
#content-based recommendations
     user_engaged_items = interaction_matrix.columns[interaction_matrix.loc[user_id] > 0]
     content_predictions = {}
     for item in user_engaged_items:
        item_index = df[df['id'] == item].index[0]
        similar_items = np.argsort(content_similarities[item_index])[-top_n:]
        content_predictions[item] = np.mean(content_similarities[item_index][similar_items])
#item-based collaborative recommendations
     item_predictions = {}
     for item in interaction_matrix.columns:
        distances, indices = item_model.kneighbors(interaction_matrix[item].values.reshape(1, -1))
        similar_items = interaction_matrix.columns[indices[0]]
        item_predictions[item] = np.mean([interaction_matrix.loc[user_id, similar_item] for similar_item in similar_items])
#hybrid recommendation
     hybrid_predictions={}
     for item in interaction_matrix.columns:
        hybrid_predictions[item] = alpha * content_predictions.get(item, 0) + (1 - alpha) * item_predictions.get(item, 0)
     top_recommendations = sorted(hybrid_predictions.items(), key=lambda x: x[1], reverse=True)[:top_n]
    # Get details of recommended items (id, category_name, video_link)
     recommended_items = []
     for item, score in top_recommendations:
        item_info = df[df['id'] == item][['id', 'category_name', 'video_link','normalized_engagement']].iloc[0]
        recommended_items.append({
            'id': item_info['id'],
            'category_name': item_info['category_name'],
            'video_link': item_info['video_link'],
            'normalized_engagement':item_info['normalized_engagement'],
            'predicted_score': score
        })
     return pd.DataFrame(recommended_items)   

In [196]:
user_id = 'afrobeezy'
recommendations = hybrid_recommendation(user_id, interaction_matrix, item_model, content_similarities, df, top_n=5, alpha=0.7)
print("Hybrid Recommended Items for User:")
print(recommendations)

Hybrid Recommended Items for User:
   id category_name                                         video_link  \
0  11         Vible  https://video-cdn.socialverseapp.com/michael_9...   
1  14         Vible  https://video-cdn.socialverseapp.com/michael_4...   
2  15         Vible  https://video-cdn.socialverseapp.com/michael_b...   
3  16         Vible  https://video-cdn.socialverseapp.com/michael_4...   
4  19         Vible  https://video-cdn.socialverseapp.com/michael_1...   

   normalized_engagement  predicted_score  
0               0.865201         0.961226  
1               0.864440         0.961226  
2               0.868342         0.961226  
3               0.863573         0.961226  
4               0.858674         0.961226  


<h2>EVALUATION METRICS</h2>

**CONTENT-BASED FILTERING**

In [162]:
recommended_posts_cb = get_recommendations(post_id=10, cosine_sim=cosine_sim, df=df, top_n=5)
actual_scores_cb = recommended_posts_cb['normalized_engagement'].values
predicted_scores_cb = recommended_posts_cb['predicted_score'].values

In [163]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Calculate metrics
mae_cb = mean_absolute_error(actual_scores_cb, predicted_scores_cb)
rmse_cb = np.sqrt(mean_squared_error(actual_scores_cb, predicted_scores_cb))

print(f"Content-Based Filtering MAE: {mae_cb}")
print(f"Content-Based Filtering RMSE: {rmse_cb}")

Content-Based Filtering MAE: 0.47748526522593326
Content-Based Filtering RMSE: 0.47958712009351206


**COLLABORATIVE FILTERING**

In [166]:
user_id = 'kinha'
recommended_items_df = recommend_for_user(user_id, interaction_matrix, model, top_n=5)

# Extract predicted scores from recommendations
predicted_scores = recommended_items_df['predicted_score'].values

# Extract actual engagement scores for the recommended items from the interaction matrix or df
actual_scores = []
for item_id in recommended_items_df['id']:
    # Get the actual engagement score for the item
    actual_score = interaction_matrix.loc[user_id, item_id] if item_id in interaction_matrix.columns else 0
    actual_scores.append(actual_score)


In [167]:
mae = mean_absolute_error(actual_scores, predicted_scores)
rmse = np.sqrt(mean_squared_error(actual_scores, predicted_scores))

print(f"Mean Absolute Error (MAE): {mae}")
print(f"Root Mean Square Error (RMSE): {rmse}")

Mean Absolute Error (MAE): 0.8899575834002065
Root Mean Square Error (RMSE): 0.9103131809132409


**HYBRID MODEL**

In [197]:
recommended_posts_hybrid = hybrid_recommendation(user_id=user_id, 
                                                 interaction_matrix=interaction_matrix, 
                                                 item_model=item_model, 
                                                 content_similarities=cosine_sim, 
                                                 df=df, top_n=5, alpha=0.7)



In [200]:
actual_scores_hybrid = recommended_posts_hybrid['normalized_engagement'].values
predicted_scores_hybrid = recommended_posts_hybrid['predicted_score'].values

In [201]:
mae_hybrid = mean_absolute_error(actual_scores_hybrid, predicted_scores_hybrid)
rmse_hybrid = np.sqrt(mean_squared_error(actual_scores_hybrid, predicted_scores_hybrid))

print(f"Hybrid Model MAE: {mae_hybrid}")
print(f"Hybrid Model RMSE: {rmse_hybrid}")

Hybrid Model MAE: 0.09402539661937545
Hybrid Model RMSE: 0.09410892821742863


In [202]:
df['mood'].unique()

array(['Happy', 'Excited', 'Neutral'], dtype=object)

<h2>COLD START PROBLEM HANDLING</h2>

In [214]:
emoji_to_mood = {
    '😊': 'Happy',
    '😃': 'Excited',
    '😐': 'Neutral',
}


In [215]:
mood_to_content = {
    "Happy": ["motivational", "fun", "positive","relaxing",  "ambient"],
    "Excited": ["high-energy", "sports", "action", "adventure"],
    "Neutral": ["calming", "nature", "meditation" "documentary", "chill"],
    }

In [216]:
def recommend_videos_by_emoji(user_emoji, df, top_n=5):
    
    # Convert emoji to mood (default to 'Neutral' if emoji not found)
    user_mood = emoji_to_mood.get(user_emoji, 'Neutral')  # Default to 'Neutral'
    
    # Debug: Check what mood was assigned
    print(f"User Mood: {user_mood}") 
    
    # Get the content categories corresponding to the user's mood
    content_categories = mood_to_content.get(user_mood, [])
    
    # Filter the content based on the mood's content categories
    # You can adjust the filtering logic to match the mood column in your dataset if needed
    filtered_content = df[df['mood'].isin(content_categories)]
    
    # If no content matches, fallback to random selection
    if filtered_content.empty:
        filtered_content = df.sample(top_n)
    
    return filtered_content[['title', 'mood', 'normalized_engagement', 'user_id']].head(top_n)

In [217]:
user_emoji = '😊'  # User is feeling happy
recommended_videos = recommend_videos_by_emoji(user_emoji, df)

# Output the recommended videos
print(recommended_videos)

User Mood: Happy
                                                 title     mood  \
320                         For God so loved the world    Happy   
228  The story of prophet Elijah proving who the re...    Happy   
258                               these orthodox monks    Happy   
193                           🚀 Best memecoins on Tron  Neutral   
56                                   Prayer before bed    Happy   

     normalized_engagement user_id  
320               0.854260   kinha  
228               0.867808   kinha  
258               0.857704   kinha  
193               0.828362   kinha  
56                0.878193   kinha  


In [218]:
df.head(1)

id                                              title  comment_count  \
0  1379  When the heart and the mind work together.. ❤️...              0   

   upvote_count  view_count  rating_count  average_rating  share_count  \
0             2          17             3              25            2   

   exit_count           created_at  ...  \
0         393  2024-11-28 19:30:23  ...   

                                       profile_url isVerified  \
0  https://assets.socialverseapp.com/profile/7.png      False   

            last_login  post_count  following_count follower_count   mood  \
0  2024-12-06 02:27:59          13                0              1  Happy   

                               content        user_id normalized_engagement  
0  Bloom Scroll Scroll until you bloom  bloomscroller              0.467583  

[1 rows x 33 columns]

In [219]:
final_data.columns

Index(['id', 'title', 'comment_count', 'upvote_count', 'view_count',
       'rating_count', 'average_rating', 'share_count', 'exit_count',
       'created_at', 'username', 'interaction_type', 'engagement_score',
       'interaction_rate', 'category_id', 'video_link', 'category_name',
       'category_count', 'category_description', 'email', 'first_name',
       'last_name', 'role', 'profile_url', 'isVerified', 'last_login',
       'post_count', 'following_count', 'follower_count', 'mood', 'content',
       'user_id', 'normalized_engagement'],
      dtype='object')